// AUTO-GENERATED by `cargo run --bin gen-native --features codegen`
// Do not edit. Source: `src/codegen.rs` IR_ELEMENTS.
// Runtime still uses org.json.JSONObject via render.El.

package git.s00d.widgets

/** Known `type` wire values for widget IR elements. */
object WireTypes {
    const val VSTACK = "vstack"
    const val HSTACK = "hstack"
    const val ZSTACK = "zstack"
    const val GRID = "grid"
    const val CONTAINER = "container"
    const val TEXT = "text"
    const val IMAGE = "image"
    const val PROGRESS = "progress"
    const val GAUGE = "gauge"
    const val BUTTON = "button"
    const val TOGGLE = "toggle"
    const val DIVIDER = "divider"
    const val DATE = "date"
    const val CHART = "chart"
    const val LIST = "list"
    const val LINK = "link"
    const val SHAPE = "shape"
    const val TIMER = "timer"
    const val CANVAS = "canvas"
    const val LABEL = "label"
    const val SPACER = "spacer"

    val ALL: Set<String> = setOf(
        VSTACK,
        HSTACK,
        ZSTACK,
        GRID,
        CONTAINER,
        TEXT,
        IMAGE,
        PROGRESS,
        GAUGE,
        BUTTON,
        TOGGLE,
        DIVIDER,
        DATE,
        CHART,
        LIST,
        LINK,
        SHAPE,
        TIMER,
        CANVAS,
        LABEL,
        SPACER,
    )
}
