// @ts-nocheck
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { ROOT, writeBlock } from "./shared.js";
export function genPermissions(report, check) {
  const src = join(ROOT, "permissions/autogenerated/reference.md");
  const body = readFileSync(src, "utf8");
  writeBlock(report, "docs/api/permissions.md", "permissions", body, check);
}
