import { defineCommand } from "citty";
import { chmodSync, copyFileSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { pluginRoot } from "../lib/paths.js";
import { detectTauriIdentifier, ensurePluginsWidgets, readTauriConf, writeTauriConf } from "../lib/tauri-conf.js";
import {
  codesignIdentities,
  identitiesHaveTeam,
  pickPreferredIdentity,
  recommendTransport,
} from "../lib/signing.js";
import { syncMacosEntitlementsFromConf, writeEntitlementsFile } from "../lib/entitlements.js";
import { copyTemplate, widgetTemplateReplacements } from "../lib/templates.js";

export interface InitMacosOptions {
  bundleId?: string;
  appGroup?: string;
  dir: string;
  force: boolean;
  applySigning: boolean;
}

export function initMacosAction(opts: InitMacosOptions): void {
  const cwd = process.cwd();
  const conf = readTauriConf(cwd);

  let bundleId = opts.bundleId;
  let appGroup = opts.appGroup;

  if (!bundleId || !appGroup) {
    if (!conf) {
      console.error(
        "ERROR: Could not find tauri.conf.json. Run from your Tauri project root, or pass --bundle-id and --app-group explicitly.",
      );
      process.exit(1);
    }
    const identifier = detectTauriIdentifier(conf);
    if (!identifier) {
      console.error("ERROR: tauri.conf.json is missing 'identifier'. Set it, or pass --bundle-id and --app-group explicitly.");
      process.exit(1);
    }
    if (!bundleId) {
      bundleId = identifier + ".widgetkit";
      console.log(`  Auto-detected bundle-id: ${bundleId}`);
    }
    if (!appGroup) {
      appGroup = "group." + identifier;
      console.log(`  Auto-detected app-group: ${appGroup}`);
    }
  }

  const widgetDir = resolve(cwd, opts.dir);
  const root = pluginRoot();
  const templateDir = join(root, "templates", "macos-widget");
  const swiftPackagePath = resolve(root, "swift");

  if (existsSync(widgetDir) && !opts.force) {
    console.error(`ERROR: ${opts.dir} already exists. Use --force to overwrite.`);
    process.exit(1);
  }

  console.log(`\nCreating macOS widget extension in ${opts.dir}...\n`);

  mkdirSync(join(widgetDir, "Sources"), { recursive: true });

  copyTemplate(
    join(templateDir, "MyWidget.swift"),
    join(widgetDir, "Sources", "MyWidget.swift"),
    widgetTemplateReplacements(appGroup),
  );
  console.log("  Created Sources/MyWidget.swift");

  writeEntitlementsFile(join(widgetDir, "TauriWidgetExtension.entitlements"), {
    appGroup,
    sandbox: true,
  });
  console.log("  Created TauriWidgetExtension.entitlements");

  writeEntitlementsFile(join(widgetDir, "App.entitlements"), {
    appGroup,
    sandbox: false,
  });
  console.log("  Created App.entitlements");

  copyTemplate(join(templateDir, "project.yml"), join(widgetDir, "project.yml"), {
    TAURI_WIDGETS_SWIFT_PATH: swiftPackagePath,
    WIDGET_BUNDLE_ID: bundleId,
  });
  console.log("  Created project.yml");

  copyFileSync(join(templateDir, "Info.plist"), join(widgetDir, "Info.plist"));
  console.log("  Created Info.plist");

  copyFileSync(join(templateDir, "build-widget.sh"), join(widgetDir, "build-widget.sh"));
  chmodSync(join(widgetDir, "build-widget.sh"), 0o755);
  console.log("  Created build-widget.sh");

  copyFileSync(join(templateDir, "embed-widget.sh"), join(widgetDir, "embed-widget.sh"));
  chmodSync(join(widgetDir, "embed-widget.sh"), 0o755);
  console.log("  Created embed-widget.sh");

  writeFileSync(
    join(widgetDir, ".gitignore"),
    "build/\n*.xcodeproj\nxcuserdata/\n# regenerated by build-widget.sh from plugins.widgets.appGroup\nApp.entitlements\nTauriWidgetExtension.entitlements\n",
  );
  console.log("  Created .gitignore");

  // Auto-patch tauri.conf.json — .appex ships via beforeBundle + macOS.files
  if (conf) {
    let modified = false;
    const data = conf.data;
    const widgetRel = opts.dir.replace(/\\/g, "/");
    const appexSrc = `./${widgetRel.replace(/^src-tauri\//, "")}/build/Build/Products/Release/TauriWidgetExtension.appex`;
    // Paths in bundle.macOS are relative to src-tauri/
    const entitlementsRel = `./${widgetRel.replace(/^src-tauri\//, "")}/App.entitlements`;
    const beforeCmd = `./${widgetRel}/build-widget.sh`;

    if (!data.build) data.build = {};
    if (!data.build.beforeBundleCommand) {
      data.build.beforeBundleCommand = beforeCmd;
      modified = true;
      console.log(`  Set build.beforeBundleCommand → ${beforeCmd}`);
    } else {
      const raw = String(data.build.beforeBundleCommand);
      const existing = raw.replace(/\s*\|\|\s*true\s*$/, "").trim();
      if (existing.includes("build-widget.sh")) {
        if (existing !== raw) {
          data.build.beforeBundleCommand = existing;
          modified = true;
          console.log("  Removed '|| true' from beforeBundleCommand");
        }
      } else {
        data.build.beforeBundleCommand = `${existing} && ${beforeCmd}`;
        modified = true;
        console.log(`  Composed build.beforeBundleCommand → ${data.build.beforeBundleCommand}`);
      }
    }

    if (!data.bundle) data.bundle = {};
    if (!data.bundle.macOS) data.bundle.macOS = {};
    const mac = data.bundle.macOS;

    if (!mac.entitlements) {
      mac.entitlements = entitlementsRel;
      modified = true;
      console.log(`  Set bundle.macOS.entitlements → ${entitlementsRel}`);
    }

    if (!mac.files) mac.files = {};
    const plugKey = "PlugIns/TauriWidgetExtension.appex";
    if (!mac.files[plugKey]) {
      mac.files[plugKey] = appexSrc;
      modified = true;
      console.log(`  Set bundle.macOS.files[${plugKey}] → ${appexSrc}`);
    }

    if (modified) {
      writeTauriConf(conf);
      console.log(`\n  Updated ${conf.path.replace(cwd + "/", "")}`);
    }

    if (opts.applySigning !== false) {
      const identities = codesignIdentities();
      const transport = recommendTransport(identities);
      const result = ensurePluginsWidgets(conf, {
        appGroup,
        transport,
        extensionBundleId: bundleId,
        force: Boolean(opts.force),
        explicitAppGroup: Boolean(opts.appGroup),
      });
      const conf2 = readTauriConf(cwd);
      if (result.wrote || !conf2?.data?.plugins?.widgets?.transport) {
        console.log(
          `  Wrote plugins.widgets (transport=${transport}${identitiesHaveTeam(identities) ? "" : " — no Team ID certificates found"})`,
        );
        if (!identitiesHaveTeam(identities)) {
          console.log(`  When a Team ID appears → switch to "appGroup" or run: npx tauri-widgets signing --apply`);
        }
      } else if (conf2?.data?.plugins?.widgets) {
        console.log(`  Kept existing plugins.widgets (transport=${conf2.data.plugins.widgets.transport})`);
      }
      const ents = syncMacosEntitlementsFromConf(cwd, conf2 || conf);
      if (ents.wrote) {
        console.log(`  Synced entitlements from plugins.widgets.appGroup (${ents.appGroup})`);
      }
    }
  }

  const preferred = pickPreferredIdentity(codesignIdentities());
  console.log(`
Done! Next steps:

  1. Install xcodegen if not already:
     brew install xcodegen

  2. Build (builds .appex, copies into Contents/PlugIns/, signs, DMG):
     pnpm tauri build

  Bundle ID:  ${bundleId}
  App Group:  ${appGroup}
${preferred ? `  Suggested:  export WIDGET_SIGN_IDENTITY="${preferred.name}"` : "  Signing:    ad-hoc (-) — use transport widgetContainer until you have a Team ID\n  Inspect:    npx tauri-widgets signing"}

  Note: embed-widget.sh is deprecated — PlugIns come from bundle.macOS.files.
  Entitlements are regenerated by build-widget.sh from plugins.widgets.appGroup.
`);
}

export const initMacos = defineCommand({
  meta: {
    name: "init-macos",
    description: "Initialize macOS widget extension in src-tauri/macos-widget/",
  },
  args: {
    "bundle-id": {
      type: "string",
      description: "Widget bundle identifier (e.g. com.example.myapp.widgetkit). Auto-detected from tauri.conf.json if omitted.",
    },
    "app-group": {
      type: "string",
      description: "App Group identifier (e.g. group.com.example.myapp). Auto-detected from tauri.conf.json if omitted.",
    },
    dir: {
      type: "string",
      description: "Target directory (default: src-tauri/macos-widget)",
      default: "src-tauri/macos-widget",
    },
    force: {
      type: "boolean",
      description: "Overwrite existing files",
      default: false,
    },
    "apply-signing": {
      type: "boolean",
      description: "Write plugins.widgets with transport inferred from codesign identities (default: true)",
      default: true,
    },
  },
  run({ args }) {
    initMacosAction({
      bundleId: args["bundle-id"],
      appGroup: args["app-group"],
      dir: args.dir,
      force: args.force,
      applySigning: args["apply-signing"] !== false,
    });
  },
});
